# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: your-email@domain.com
brand: Wang Cheng
headline: iOS dev, fitness and Sports talent
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2017 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: wangchengapp@gmail.com
phone: +1-316-277-9177

# Tracking
googleAnalitycsID: UA-83933844-1

